#!/bin/sh

dir=$(dirname $0)

opts=""
while [ 0 -lt $# ]
do
	case "$1" in
	"--ssl")
		opts="${opts} --ssl"
		shift
		;;
	*)
		break
		;;
	esac
done

"${dir}/run_tests" --java ${opts} --filter "${dir}/tests/java_filter" "$@"
