#!/bin/sh

test_result()
{
	local result status t

	t="${1}"
	status="${2}"
	if [ "${status}" = 0 ]; then
		result="OK"
	else
		result="NG"
	fi
	echo "${t}: ${result}"
}

dir="$(dirname $0)/tests"
arch=$(uname -p)
find "${dir}" -name "test_*" | sort | while read t
do
	echo "******** ${t} ********"

	unset args cmd status test_status test_stdout
	. "${t}"

	"${dir}/tester/tester" "${dir}/${arch}/${cmd}" ${args}
	status="${?}"

	for f in test_status test_stdout
	do
		s=$(type ${f} 2> /dev/null | sed -e "s/^.* is a //")
		if [ "${s}" != "shell function" ]; then
			continue
		fi
		${f} "${status}"
		test_result "${t}" "${?}"
	done
done
