#!/bin/sh

test_result()
{
	local result status t

	t="${1}"
	status="${2}"
	if [ "${status}" = 0 ]; then
		result="OK"
	else
		result="NG"
	fi
	echo "${t}: ${result}"
}

dir="$(dirname $0)"
tests_dir="${dir}/tests"
tester="${tests_dir}/tester/tester"
tmp_dir="${dir}/tmp.tests"
arch=$(uname -p)

rm -rf "${tmp_dir}" || exit 1
mkdir -p "${tmp_dir}" || exit 1

find "${tests_dir}" -name "test_*" | sort | while read t
do
	echo "******** ${t} ********"

	unset args cmd status
	unset -f test_status test_stdout
	. "${t}"

	exe="${tests_dir}/${arch}/${cmd}"
	stdout_log="${tmp_dir}/stdout.log"
	"${tester}" "${exe}" ${args} > "${stdout_log}"
	status="${?}"

	type test_status > /dev/null 2>&1
	if [ "${?}" = 0 ]; then
		test_status "${status}"
		test_result "${t}" "${?}"
	fi
	type test_stdout > /dev/null 2>&1
	if [ "${?}" = 0 ]; then
		test_stdout "$(cat "${stdout_log}")"
		test_result "${t}" "${?}"
	fi
done

rm -rf "${tmp_dir}" || exit 1
