#!/bin/sh

test_result()
{
	local result status t

	t="${1}"
	status="${2}"
	if [ "${status}" = 0 ]; then
		result="OK"
	else
		result="NG"
	fi
	echo "${t}: ${result}"
}

dir="$(dirname $0)/tests"
arch=$(uname -p)
find "${dir}" -name "test_*" | sort | while read t
do
	echo "******** ${t} ********"

	unset args cmd status test_status test_stdout
	. "${t}"

	stdout_log="/tmp/fsyscall.run_tests.stdout_log"
	"${dir}/tester/tester" "${dir}/${arch}/${cmd}" ${args} > "${stdout_log}"
	status="${?}"

	s=$(type test_status 2> /dev/null | sed -e "s/^.* is a //")
	if [ "${s}" = "shell function" ]; then
		test_status "${status}"
		test_result "${t}" "${?}"
	fi
	s=$(type test_stdout 2> /dev/null | sed -e "s/^.* is a //")
	if [ "${s}" = "shell function" ]; then
		test_stdout "$(cat "${stdout_log}")"
		test_result "${t}" "${?}"
	fi
done
