
CC=		clang
SRCS=		${PROG}.c
ADDITIONAL+=	Makefile ../Makefile.cprog
CFLAGS+=	-O0 -g -I../include -include tiny_runtime.h
LDFLAGS+=	-L../tiny_runtime -nostdlib
LDADD+=		-ltiny_runtime
WITHOUT_MAN=	yes

.include <bsd.prog.mk>

# vim: filetype=make
