
LIBDIR=	do_stat_test print_stat_member lib tiny_runtime
SUBDIR=	${LIBDIR} access bind close close_twice connect dup dup_and_close exit \
	fcntl fork fstat fstatfs getdirentries getegid geteuid getgid \
	getpeername_error getpeername_family getpeername_path getpid \
	getresuid_ruid getresuid_euid getresuid_suid getsockname_family \
	gettimeofday_dsttime gettimeofday_minuteswest gettimeofday_sec \
	gettimeofday_usec getuid ioctl issetugid lseek lstat open poll_in \
	poll_out poll_timeout pread read readlink select select2 socket stat \
	write writev

.include <bsd.subdir.mk>
