
LIBDIR=	do_stat_test print_stat_member lib tiny_runtime
SUBDIR=	${LIBDIR} accept access bind chdir chdir_access chdir_error \
	chdir_lstat chdir_open chdir_readlink chdir_stat chmod chmod_error \
	close close_twice connect dup dup2 dup2_EBADF dup2_in_use dup2_nothing \
	dup_and_close execve exit fcntl fork fstat fstatfs getdirentries \
	getegid geteuid getgid getpeername_error getpeername_family \
	getpeername_path getpeername_server getpid getresgid_egid \
	getresgid_rgid getresgid_sgid getresuid_ruid getresuid_euid \
	getresuid_suid getsockname_family getsockname_server getsockopt \
	gettimeofday_dsttime gettimeofday_minuteswest gettimeofday_sec \
	gettimeofday_usec getuid ioctl issetugid kill listen lseek lstat mkdir \
	open poll_in poll_out poll_timeout pread read readlink select select2 \
	setsockopt sigaction socket stat wait4_rusage wait4_status \
	wait4_successful write writev

.include <bsd.subdir.mk>
