
LIB=		start_slave
TOP_DIR=	../..
CFLAGS=		-I${TOP_DIR}/include
LIB_DIR=	${TOP_DIR}/lib
LDADD=		${LIB_DIR}/close_or_die/libclose_or_die.a \
		${LIB_DIR}/fork_or_die/libfork_or_die.a \
		${LIB_DIR}/pipe_or_die/libpipe_or_die.a

.include "../Makefile.lib"
