
PROG=		pid
SRCS=		main.c
TOP_DIR=	../../..
CFLAGS=		-I${TOP_DIR}/include
LIB_DIR=	${TOP_DIR}/lib
LDADD=		${LIB_DIR}/encode/libencode.a ${LIB_DIR}/die/libdie.a
WITHOUT_MAN=	yes

.include <bsd.prog.mk>
