#!/usr/local/bin/python

from os.path import basename
from re import compile
from sys import argv, exit

excludes = [
        compile(r"\Atest_[fl]?stat_(?!size)")
        ]

name = basename(argv[1])
exit(1 if 0 < len([ex for ex in excludes if ex.match(name) is not None]) else 0)

# vim: tabstop=4 shiftwidth=4 expandtab softtabstop=4
