
OBJS=	${SRCS:.S=.o}

all: ${LIB}

${LIB}: ${OBJS}
	${AR} cq ${.TARGET} ${OBJS}

${SRCS}: Makefile

.S.o:
	nasm -f ${FORMAT} -o ${.TARGET} -l ${.ALLSRC:.S=.lst} ${.ALLSRC}

clean:
	rm -f ${OBJS} ${LIB} *.lst

# vim: filetype=make
