
NASMFLAGS+=	-I${MACHINE_ARCH}
LST=		${.ALLSRC:M*.S:.S=.lst}
OBJS=		${SRCS:.S=.o}

all: ${LIB}

${LIB}: ${OBJS}
	${AR} cq ${.TARGET} ${OBJS}

${OBJS}: ${ADDITIONAL} Makefile

.S.o:
	nasm -f ${FORMAT} -o ${.TARGET} -l ${LST} ${NASMFLAGS} ${.ALLSRC:M*.S}

clean:
	rm -f ${OBJS} ${LIB} *.lst

# vim: filetype=make
