#if !defined(FSYSCALL_PRIVATE_COMMAND_CODE_H_INCLUDED)
#define	FSYSCALL_PRIVATE_COMMAND_CODE_H_INCLUDED

#define	CALL_EXIT		42
#define	RET_EXIT		43
#define	CALL_READ		44
#define	RET_READ		45
#define	CALL_WRITE		46
#define	RET_WRITE		47
#define	CALL_OPEN		48
#define	RET_OPEN		49
#define	CALL_CLOSE		50
#define	RET_CLOSE		51
#define	CALL_LINK		52
#define	RET_LINK		53
#define	CALL_GETPID		54
#define	RET_GETPID		55
#define	CALL_GETUID		56
#define	RET_GETUID		57
#define	CALL_GETEUID		58
#define	RET_GETEUID		59
#define	CALL_ACCESS		60
#define	RET_ACCESS		61
#define	CALL_DUP		62
#define	RET_DUP			63
#define	CALL_GETEGID		64
#define	RET_GETEGID		65
#define	CALL_GETGID		66
#define	RET_GETGID		67
#define	CALL_IOCTL		68
#define	RET_IOCTL		69
#define	CALL_READLINK		70
#define	RET_READLINK		71
#define	CALL_FCNTL		72
#define	RET_FCNTL		73
#define	CALL_SELECT		74
#define	RET_SELECT		75
#define	CALL_WRITEV		76
#define	RET_WRITEV		77
#define	CALL_STAT		78
#define	RET_STAT		79
#define	CALL_FSTAT		80
#define	RET_FSTAT		81
#define	CALL_LSTAT		82
#define	RET_LSTAT		83
#define	CALL_GETDIRENTRIES	84
#define	RET_GETDIRENTRIES	85
#define	CALL_ISSETUGID		86
#define	RET_ISSETUGID		87
#define	CALL_FSTATFS		88
#define	RET_FSTATFS		89
#define	CALL_PREAD		90
#define	RET_PREAD		91
#define	CALL_MMAP		92
#define	RET_MMAP		93
#define	CALL_LSEEK		94
#define	RET_LSEEK		95
#define	CALL_SOCKET		96
#define	RET_SOCKET		97
#define	CALL_CONNECT		98
#define	RET_CONNECT		99
#define	CALL_POLL		100
#define	RET_POLL		101
#define	CALL_RECVFROM		102
#define	RET_RECVFROM		103
#define	CALL_PIPE		104
#define	RET_PIPE		105
#define	CALL_FORK		106
#define	RET_FORK		107

#endif
