#if !defined(FSYSCALL_PRIVATE_COMMAND_NAME_H_INCLUDED)
#define	FSYSCALL_PRIVATE_COMMAND_NAME_H_INCLUDED

#define	CALL_NAMES	{	\
	"CALL_EXIT",		\
	"CALL_READ",		\
	"CALL_WRITE",		\
	"CALL_OPEN",		\
	"CALL_CLOSE",		\
	"CALL_LINK",		\
	"CALL_GETPID",		\
	"CALL_GETUID",		\
	"CALL_GETEUID",		\
	"CALL_ACCESS",		\
	"CALL_DUP",		\
	"CALL_GETEGID",		\
	"CALL_GETGID",		\
	"CALL_IOCTL",		\
	"CALL_READLINK",	\
	"CALL_FCNTL",		\
	"CALL_SELECT",		\
	"CALL_WRITEV",		\
	"CALL_STAT",		\
	"CALL_FSTAT",		\
	"CALL_LSTAT",		\
	"CALL_GETDIRENTRIES",	\
	"CALL_ISSETUGID",	\
	"CALL_FSTATFS",		\
	"CALL_PREAD",		\
	"CALL_MMAP",		\
	"CALL_LSEEK",		\
	"CALL_SOCKET",		\
	"CALL_CONNECT"		\
}
#define	RET_NAMES	{	\
	"RET_EXIT",		\
	"RET_READ",		\
	"RET_WRITE",		\
	"RET_OPEN",		\
	"RET_CLOSE",		\
	"RET_LINK",		\
	"RET_GETPID",		\
	"RET_GETUID",		\
	"RET_GETEUID",		\
	"RET_ACCESS",		\
	"RET_DUP",		\
	"RET_GETEGID",		\
	"RET_GETGID",		\
	"RET_IOCTL",		\
	"RET_READLINK",		\
	"RET_FCNTL",		\
	"RET_SELECT",		\
	"RET_WRITEV",		\
	"RET_STAT",		\
	"RET_FSTAT",		\
	"RET_LSTAT",		\
	"RET_GETDIRENTRIES",	\
	"RET_ISSETUGID",	\
	"RET_FSTATFS",		\
	"RET_PREAD",		\
	"RET_MMAP",		\
	"RET_LSEEK",		\
	"RET_SOCKET",		\
	"RET_CONNECT"		\
}

#endif
