
SUBDIR=	atoi_or_die close_or_die command die encode fork_or_die geterrorname \
	hub io io_or_die list log malloc_or_die payload pipe_or_die \
	read_sockaddr run_master select start_slave

.include <bsd.subdir.mk>
