
SUBDIR=	atoi_or_die close_or_die command die encode fork_or_die geterrorname \
	hub io io_or_die list log malloc_or_die payload pipe_or_die \
	read_sockaddr select start_master start_slave

.include <bsd.subdir.mk>
